#!/usr/bin/env python3
"""
Chinese versions — 不是翻译，是重写。
先理解原文论点，再用中文思维重新写。
保留观点和逻辑结构，但句子组织、用词、节奏全部按中文来。
"""

# ═══ 文章一：循环取代了函数 ═══
POST1 = {
    "date": ("July 24, 2026", "2026年7月24日"),
    "read": ("5 min read", "约 5 分钟"),
    "title": ("The Loop Is the New Function", "函数的时代结束了"),
    "deck": ("For 70 years the function was the atom of software. Now it's the loop. What changes when code stops running once and starts running forever?",
             "函数，做了七十年软件的基本单元。现在轮到循环了。代码不再跑一次就完，而是一直跑下去——这意味着什么？"),

    "p1": ("Every programmer alive has internalized the same mental model: software is built from functions. You define an input, you write a transformation, you get an output. <code>f(x) = y</code>. The function is deterministic. It runs once. It stops. If it gives you the wrong answer, you debug the logic, fix it, run it again. This model is so deeply embedded in our tools, languages, and brains that we don't even question it anymore. It's just how software works.",
           "所有程序员都共享同一个底层假设：软件就是一堆函数。输入进去，做点处理，输出出来。<code>f(x) = y</code>。函数是确定的——跑一次，停。错了？查逻辑、改代码、再跑。这套东西嵌进了我们的语言、工具、甚至直觉，深到我们从不去怀疑它。软件就该是这样。"),
    "p2": ("But something is shifting underneath us. The software being built in 2026 doesn't work like that. AI agents don't transform an input into an output and stop. They observe, act, evaluate, adjust, and repeat. They run in loops that don't have a clean termination condition. The fundamental unit isn't a function call — it's a cycle. And the engineering discipline emerging to design those cycles has a new name: loop engineering.",
           "但游戏规则正在改变。2026 年的软件不是这样的。AI 智能体不会算完就停。它会看、会做、会判断对不对、会调整，然后从头来过。它跑在一个循环里，而这个循环没有一个干净的「跑完了」的标志。这里的基本单位不是函数调用，而是一圈又一圈的迭代。设计这种迭代的工程，有了个新名字：循环工程。"),
    "caption1": ("The function runs and stops. The loop runs and learns. Different physics entirely.",
                 "函数跑完就停。循环跑着跑着会学。完全不是一回事。"),
    "h2_1": ("The death of determinism", "确定性回不来了"),
    "p3": ("Here's the uncomfortable truth nobody in the AI engineering discourse wants to say out loud: we lost determinism, and we're not getting it back. A function that calls an LLM is, by definition, not deterministic. The same input can produce different outputs on different days. This isn't a bug. It's the physics of the new substrate. And pretending otherwise — wrapping a model call in a function signature and hoping it behaves like <code>parseInt</code> — is the most common architectural mistake teams make in 2026.",
            "AI 工程圈有个谁都不愿明说的事实：确定性没了，而且不会回来。一个调 LLM 的函数，从定义上就不确定。同样的输入，今天和明天的输出可能不一样。这不是 bug——这是新技术底层的物理规律。把模型调用包在函数签名里，指望它像 <code>parseInt</code> 那样规规矩矩，是 2026 年最常见的架构错误。"),
    "p4": ("Loop engineering accepts this reality and builds around it. Instead of trying to make models deterministic, you design systems that converge on correctness through repetition. The agent writes code, runs tests, reads the errors, and tries again. Each iteration isn't guaranteed to be right — but the loop, as a whole, is designed to converge. The engineering isn't in the individual step. It's in the shape of the cycle.",
           "循环工程的态度是：既然不确定，那就接受它，然后换一套设计思路。不再追求让模型变确定，而是设计一个靠反复迭代逼近正确的系统。智能体写代码、跑测试、看报错、改、再跑。单独一轮不保证对，但整个循环被设计成会收敛——会越来越接近正确。工程的重点不在某一轮，而在循环的形状。"),
    "caption2": ("A single function call starts wrong and stays wrong. A loop starts wrong and converges.",
                 "单次调用错了就一直错。循环会自己纠过来。"),
    "blockquote1": ("We spent 70 years optimizing for the fastest path from input to output. Now we're optimizing for the shortest path from wrong to right. Those are fundamentally different engineering problems.",
                    "过去七十年，我们优化的是「从输入到输出」怎么最快。现在要优化的是「从错到对」怎么最快。这是两个完全不同的工程问题。"),
    "h2_2": ("What a loop engineer actually does", "循环工程师在做什么"),
    "p5": ('A traditional engineer asks: "How do I write the function that transforms this input into the correct output?" A loop engineer asks an entirely different set of questions: "How many iterations should this cycle take before I give up? What signal tells the agent it\'s done? What context needs to persist between iterations? Where does the feedback come from — tests, human review, another model? What\'s the cost ceiling per loop before this becomes uneconomic?"',
           '传统工程师的问题是：「怎么写一个函数，把这个输入变成正确的输出？」循环工程师问的完全不一样：「这个循环最多跑几轮？什么信号说明做完了？哪些东西要在迭代之间记住？反馈从哪来——测试、人工审查、还是另一个模型？每一轮最多花多少钱？」'),
    "p6": ('These are not software engineering questions. They\'re closer to control theory — the discipline that gave us thermostats, autopilots, and cruise control. A thermostat doesn\'t "compute" the right temperature. It runs a loop: measure, compare, adjust, repeat. The correctness lives in the loop design, not in any single measurement. Loop engineering is essentially bringing control theory into software, whether we admit it or not.',
           '这些问题不是传统软件工程的。它们更接近控制论——做恒温器、自动驾驶、定速巡航的那门学问。恒温器不会「算」出正确的温度。它做的是一件很朴素的事：量、比、调、再来一遍。正确性不在某一次测量里，而在这个循环的设计里。说到底，循环工程就是把控制论搬进了软件——不管我们叫不叫这个名字。'),
    "p7": ("The practical implications are wild. Your test suite isn't just a quality gate anymore — it's the feedback signal that keeps the loop converging. Your CI/CD pipeline isn't just deployment infrastructure — it's the harness that decides whether the agent's output is safe to ship. Your codebase isn't just a set of instructions — it's the context window that shapes what the agent does next. Everything gets reinterpreted through the lens of the loop.",
           "这会带来很大的连锁反应。你的测试套件不再只是质量关卡——它变成了让循环收敛的反馈信号。你的 CI/CD 不再只是部署工具——它变成了决定智能体产出能不能上线的裁判。你的代码库不再只是一堆指令——它变成了影响智能体下一步行为的上下文。所有的东西，都要放到循环的视角下重新理解。"),
    "h2_3": ("The harness is the product", "脚手架才是产品"),
    "p8": ('This is why "harness engineering" keeps coming up in the same conversations as loop engineering. The harness is the scaffolding around the model: the system prompt, the tool definitions, the retrieval pipeline, the evaluation criteria, the retry logic, the guardrails. When your core compute is probabilistic, the deterministic wrapper around it becomes the actual product. OpenAI knows this — it\'s why Codex and ChatGPT Work are built as harnesses, not models. Anthropic knows it — Claude\'s tool-use protocol is a harness specification. The model is a commodity. The loop is the moat.',
           '这也是为什么「脚手架工程」总和循环工程一起出现。脚手架是模型外面那一层：系统提示、工具定义、检索管线、评估标准、重试逻辑、安全边界。当你的核心计算是概率性的，外面这层确定性的壳就成了真正的产品。OpenAI 懂——Codex 和 ChatGPT Work 是按脚手架设计的，不是按模型。Anthropic 也懂——Claude 的工具调用协议本身就是一个脚手架规范。模型是通用的，循环才是护城河。'),
    "caption3": ("The harness: deterministic scaffolding around a probabilistic core. This is the actual product.",
                 "脚手架：在概率性的核心外面，搭一层确定性的壳。这才是真正的产品。"),
    "p9": ("I think most teams are still treating AI features as function calls with extra steps. They wrap a prompt in an API endpoint, ship it, and are confused when it works perfectly in testing and degrades in production. The degradation isn't a model problem. It's a loop problem. There's no feedback signal. No convergence criteria. No iteration. Just a single-shot function call that either works or doesn't, with no mechanism to improve itself.",
           "大多数团队还在用函数思维做 AI。写个 prompt，包成 API，上线。测试时好好的，上了生产就开始掉链子，然后懵了。掉链子不是模型的问题——是循环的问题。没有反馈信号，没有收敛标准，没有迭代。就是一锤子买卖，对不对都没法自我修正。"),
    "p10": ('The teams winning at AI engineering in 2026 are the ones who stopped asking "how do I write this function?" and started asking "how do I design this loop?" The answer looks less like programming and more like gardening. You don\'t build a garden by placing each leaf. You design the conditions — soil, water, light — and let the system grow toward what you want. The loop is your garden bed. The model is the seed. Your job is to design the conditions for convergence.',
            '2026 年做得好的团队，已经不问「这个函数怎么写」了。他们问的是「这个循环怎么设计」。这个问题的答案不太像编程，更像是种地。你不可能一棵一棵去摆叶子。你做的是把条件弄好——土壤、水、阳光——然后让它自己朝你要的方向长。循环是你的地，模型是种子。你的工作是创造让它收敛的条件。'),
    "p11": ("That's the shift. And it's bigger than any individual model release. The function was a good run. But the loop is where we live now.",
            "这就是转变。它比任何一次模型发布都大。函数的时代很精彩。但现在，我们活在循环里。"),

    # SVG text
    "svg_classic_label": ("CLASSIC SOFTWARE", "传统软件"),
    "svg_input": ("input", "输入"),
    "svg_fx_det": ("deterministic · runs once", "确定性 · 跑一次"),
    "svg_output": ("output", "输出"),
    "svg_wrong_q": ("Wrong answer?", "结果不对？"),
    "svg_debug": ("Debug the function.", "调函数。"),
    "svg_code_product": ("The code is the product.", "代码就是产品。"),
    "svg_ainative_label": ("AI-NATIVE SOFTWARE", "AI 原生软件"),
    "svg_observe": ("Observe", "观察"),
    "svg_observe_sub": ("read context", "读上下文"),
    "svg_act": ("Act", "行动"),
    "svg_act_sub": ("call tools", "调工具"),
    "svg_eval": ("Evaluate", "评估"),
    "svg_eval_sub": ("check result", "看结果"),
    "svg_adjust": ("Adjust", "调整"),
    "svg_adjust_sub": ("update plan", "改方案"),
    "svg_redesign": ("Redesign the loop.", "重新设计循环。"),
    "svg_harness_product": ("The harness is the product.", "脚手架才是产品。"),
    "svg_iterations": ("Iterations", "迭代次数"),
    "svg_error": ("Error", "误差"),
    "svg_converged": ("converged", "已收敛"),
    "svg_attempt1": ("Attempt 1", "第 1 轮"),
    "svg_attempt2": ("Attempt 2", "第 2 轮"),
    "svg_attempt3": ("Attempt 3", "第 3 轮"),
    "svg_single_call": ("Single function call →", "单次调用 →"),
    "svg_high_error": ("high error, no recovery", "误差大，不会自纠"),
    "svg_loop_converges": ("Loop converges →", "循环收敛 →"),
    "svg_error_zero": ("error → 0 over iterations", "误差趋近零"),
    "svg_harness_label": ("THE HARNESS (deterministic)", "脚手架（确定性）"),
    "svg_sysprompt": ("System Prompt", "系统提示"),
    "svg_tooldefs": ("Tool Definitions", "工具定义"),
    "svg_rag": ("Retrieval (RAG)", "检索 (RAG)"),
    "svg_guardrails": ("Guardrails", "安全边界"),
    "svg_llm": ("LLM", "LLM"),
    "svg_prob": ("probabilistic", "概率性"),
    "svg_commodity": ("commodity", "通用商品"),
    "svg_testsuite": ("Test Suite", "测试套件"),
    "svg_evalcrit": ("Eval Criteria", "评估标准"),
    "svg_retrylogic": ("Retry Logic", "重试逻辑"),
    "svg_cicd": ("CI/CD Gate", "CI/CD 关卡"),
    "svg_feedback": ("feedback signal → next iteration", "反馈 → 下一轮"),
    "svg_context_in": ("context in", "上下文进"),
    "svg_signal_out": ("signal out", "信号出"),
}

# ═══ 文章二：意大利面和 API 账单 ═══
POST2 = {
    "date": ("July 25, 2026", "2026年7月25日"),
    "read": ("6 min read", "约 6 分钟"),
    "title": ("Spaghetti With API Bills", "意大利面与 API 账单"),
    "deck": ("Most multi-agent systems aren't architectures. They're distributed prompts with a billing problem. The fix is older than AI itself.",
             "大部分所谓的「多智能体系统」，根本算不上架构。不过是一个 prompt 拆成几份，每份都在烧钱。解法比 AI 本身还老。"),

    "p1": ('Most teams building "multi-agent systems" in 2026 are not building systems. They have taken a single oversized prompt, sliced it across twenty agents, and called the result an architecture. The agents share ambiguous context. They return free-form text. They repeat each other\'s research and bill for the privilege. When one model\'s output format drifts — and it will drift — the entire chain collapses into a stack trace nobody can debug. This is not orchestration. It is spaghetti with API bills.',
           '2026 年大多数做「多智能体系统」的团队，做出来的根本不是系统。他们做的事其实是：把一个过大的 prompt 切成十几份，分给十几个智能体，然后管这个叫架构。这些智能体共享着含糊不清的上下文，互相吐自由格式的文本，做着重叠的工作——而且每一步都在花钱。只要其中一个模型的输出格式飘了一下（一定会飘），整条链就断了，变成一堆没人看得懂的报错。这不叫编排。这是意大利面，还附赠 API 账单。'),
    "p2": ('The pattern is common enough to be a punchline. A team reads that agents are the future, stands up a coordinator, fans out a dozen workers, wires them together with string and a JSON schema, and ships. For two weeks it looks like magic. Then reality arrives: token costs triple, latency balloons, outputs turn inconsistent, and nobody can explain why the system returned what it returned. The instinct is to blame the model. The model is rarely the problem. The problem is that there was never an architecture — only a distribution.',
           '这套流程已经普遍到可以当段子讲了。某个团队看到「智能体是未来」，于是搭一个调度器、铺十几个 worker、用 JSON schema 加胶水把它们粘起来、上线。头两周，像魔法一样好用。然后现实开始追上来：token 费翻三倍、延迟飙升、输出变得不可预测，没人能解释系统为什么返回了那个结果。第一反应是怪模型。但模型通常不是问题。问题是——从头到尾就没有架构，只是做了个分发。'),
    "caption1": ("Distribution is not design. Tangled agents share ambiguity; a graph assigns each decision to exactly one node and every edge a contract.",
                 "分发不是设计。一堆智能体纠缠在一起，只会共享含糊；而图，会把每个决策交给一个明确的节点，每条边带上一个契约。"),
    "h2_1": ("The two software crises", "两次软件危机"),
    "p3": ("The original software crisis, named in 1968, was defined by a single failure mode: systems had grown too large for any one person to understand. Code outgrew human comprehension, and the resulting bugs, overruns, and collapses felt existential. The discipline that emerged in response — modular decomposition, abstract data types, interfaces with contracts — was aimed at one specific terror. Every major idea in software engineering since, from objects to services to microservices, is a variation on the same move: break a large system into replaceable parts that speak to each other through strict contracts.",
           "1968 年，人们第一次给「软件危机」命名。核心问题只有一个：系统大到没有任何一个人能完全看懂。代码的复杂度超过了人脑的承受范围，bug、超期、项目崩盘接踵而至，感觉整个行业都要完。后来长出来的那套东西——模块化、抽象数据类型、带契约的接口——都是为了对付这一个恐惧。此后几十年，软件工程里几乎所有的大想法，从面向对象到服务化到微服务，都是同一个动作的不同版本：把大系统拆成可以替换的零件，零件之间通过严格的契约来沟通。"),
    "p4": ("The new software crisis is the mirror image, and it is arriving faster. It is not too much code. It is too many agents with no architecture between them. An agent is a probabilistic component that produces unstructured output, drifts between versions, and costs money every time it runs. Wire enough of them together without contracts and you have rebuilt the 1968 crisis on a new substrate — except now the components lie, hallucinate, and send invoices.",
           "新的软件危机是镜像版，而且来得更快。问题不再是代码太多，而是智能体太多，中间没有架构。智能体是一种概率性组件——产出是非结构化的、版本之间会漂移、每跑一次都花钱。把这些东西不加约束地串在一起，等于在新的技术底座上重演了 1968 年的危机。只不过这次的零件更刺激：它们会说谎、会编造、还会给你寄账单。"),
    "p5": ("The fix is the same fix, rediscovered. Graph engineering is the application of a fifty-year-old lesson to AI: one node owns one decision, one edge carries structured evidence, ordinary code handles the deterministic work, routers decide which branch continues, verifiers reject unsupported conclusions, and the strongest model sees only what survives.",
           "解药是同一副解药，只是被重新发现了。图工程，本质上是把五十年的老教训用在 AI 上：一个节点只负责一个决策；一条边只承载结构化的证据；确定的活交给普通代码；路由器决定接下来走哪条路；验证器把站不住脚的结论拦住；而最强的模型，只看那些通过了所有关卡的东西。"),
    "caption2": ("The old crisis was unmanageable code; the new one is unmanaged agents. Both collapse into the same architectural cure.",
                 "上一次危机，是代码管不了。这一次，是智能体管不了。但解药是同一个。"),
    "h2_2": ("Replaceability is the moat", "可替换性才是护城河"),
    "p6": ("Here is the claim that matters most. The next durable advantage in AI will not be a single permanent model. It will be a system that keeps working when the model changes. Models are being swapped, repriced, deprecated, and leapfrogged every quarter. A system whose correctness depends on one irreplaceable model is a system with an expiration date. A system in which every node is replaceable is a system with a future.",
           "最重要的一句话：AI 领域下一个持久的优势，不在于拥有某个不可替代的模型。而在于拥有一个——模型换了还能继续跑的系统。模型每个季度都在被替换、改价、弃用、被超越。如果你的系统正确性绑死在某个模型上，那这个系统就是有保质期的。但如果每个节点都能被替换，这个系统就有未来。"),
    "p7": ("This is what makes the graph, not the agent, the unit of value. In a well-designed graph, a cheap model handles extraction. A specialist inspects security. A skeptical agent attacks the result. A frontier model renders the final judgment — and it does so without ever carrying the entire workflow inside its context window. Each role is a slot. Each slot accepts any model that satisfies the contract. When a better model lands next month, it slides into the slot. When a vendor disappears, the slot survives.",
           "这就是为什么价值的单位是图，而不是智能体。在一个设计良好的图里：便宜的模型做信息抽取；专门的模型审查安全；一个唱反调的智能体负责挑刺；前沿模型只做最终裁决——而且它不需要把整个流程塞进自己的上下文窗口。每个角色是一个卡槽。每个卡槽接受任何符合契约的模型。下个月出了更好的模型？插进去就行。供应商跑路了？卡槽还在。"),
    "caption3": ("Roles are owned; models are rented. The architecture is the only durable asset.",
                 "角色是自己的，模型是租来的。架构才是你真正拥有的东西。"),
    "blockquote1": ("The original software crisis taught engineers to stop writing programs and start writing replaceable parts. The agentic crisis will teach the same lesson, again, to a generation that thought it had skipped the class.",
                    "第一次软件危机教会了工程师一件事：别再写那种不可拆分的庞然大物了，开始写可以替换的零件。智能体危机会把同一堂课再上一遍——给一代以为自己逃过这门课的人。"),
    "h2_3": ("The discipline returns", "老规矩又回来了"),
    "p8": ("What is being rediscovered is not glamorous. It is interfaces, contracts, typed edges, separation of concerns. The novelty is that these ideas now govern not just deterministic code but probabilistic components that must be governed more strictly precisely because they are not trustworthy on their own. The graph is a discipline of distrust: structure compensates for the unreliability of the nodes.",
           "被重新发现的，不是什么时髦的东西。就是接口、契约、类型化的边、关注点分离——那些老掉牙的软件工程原则。新鲜的是，这些原则现在不只管确定性代码，还要管那些概率性的组件。而且恰恰因为它们自己不靠谱，反而需要更严格的约束。图的本质，是一种制度化的不信任：既然每个节点都不可靠，那就靠结构来兜底。"),
    "p9": ("Notice what this discipline removes from the frontier model's shoulders. It no longer carries the whole workflow in one context window. It no longer has to be simultaneously the reader, the verifier, and the decider. The work is staged across a pipeline, and by the time a token reaches the strongest model, it has already been filtered, typed, and corroborated. The expensive model spends its budget on judgment, not on janitorial work. Costs fall. Latency falls. And, counterintuitively, quality rises — because every conclusion now arrives with a chain of evidence attached to it rather than the vibes of a single large prompt.",
           "注意这套规矩从前沿模型的肩上卸掉了多少东西。它不再需要一个人扛整个流程。它不再同时当读者、当裁判、当决策者。工作被分到管道的不同阶段。等数据终于抵达最强的模型时，该过滤的过滤了，该分类的分类了，该交叉验证的也验过了。贵的模型把算力花在判断上，不花在打杂上。成本降了，延迟降了。而且出乎意料的是，质量反而升了——因为每个结论背后都拖着一条证据链，而不是靠一个大 prompt 凭感觉拍脑袋。"),
    "p10": ("The teams that win will be the ones who stop measuring how clever their agents are and start measuring how replaceable they are. Cleverness is a property of the model, and the model is a borrowed asset. Replaceability is a property of the architecture, and the architecture is the only thing actually owned.",
            "能赢的团队，不再比谁的智能体更聪明，而是比谁的智能体更好替换。聪明是模型的事——而模型是借来的。可替换性是架构的事——而架构才是你自己的。"),
    "p11": ("Spaghetti with API bills is the default state of multi-agent development in 2026. It is what happens when distribution is mistaken for design. The exit is older than the industry that needs it. Draw the graph. Type the edges. Make every node disposable. Then, and only then, does adding another agent make the system stronger instead of merely more expensive.",
            "意大利面加 API 账单，是 2026 年多智能体开发的默认状态。把分发当成了设计，就会变成这样。出路比这个需要它的行业还老。画图。给每条边定好类型。让每个节点都可以被扔掉。做到这些之后——也只有做到这些之后——增加一个智能体才会让系统更强，而不只是更贵。"),

    # SVG
    "svg_dist_label": ("DISTRIBUTED PROMPT", "分布式 Prompt"),
    "svg_dist_sub": ("ambiguous context · repeated work · invoice per hop", "上下文含糊 · 重复干活 · 每一跳都收钱"),
    "svg_graph_label": ("GRAPH ENGINEERING", "图工程"),
    "svg_rawinput": ("raw input", "原始输入"),
    "svg_extract": ("extract", "抽取"),
    "svg_router": ("router", "路由"),
    "svg_verify": ("verify", "验证"),
    "svg_judge": ("judge", "裁决"),
    "svg_evidence": ("evidence", "证据"),
    "svg_typed_edge": ("typed edge", "类型化边"),
    "svg_graph_sub": ("one node = one decision · every edge carries a contract", "一个节点 = 一个决策 · 每条边都有契约"),
    "svg_1968": ("1968 CRISIS", "1968 年危机"),
    "svg_too_code1": ("too much code", "代码太多"),
    "svg_too_code2": ("for one mind", "一个人搞不定"),
    "svg_2026": ("2026 CRISIS", "2026 年危机"),
    "svg_too_agents1": ("too many agents", "智能体太多"),
    "svg_too_agents2": ("no architecture", "没有架构"),
    "svg_replaceable": ("REPLACEABLE PARTS", "可替换零件"),
    "svg_strict_contracts": ("with strict contracts", "带严格契约"),
    "svg_same_lesson": ("the same lesson, twice", "同一堂课，上两遍"),
    "svg_any_model": ("ANY MODEL FITS THE CONTRACT", "任何模型都能插"),
    "svg_slot_extract": ("SLOT · extractor", "卡槽 · 抽取"),
    "svg_cheap_model": ("cheap model", "廉价模型"),
    "svg_slot_specialist": ("SLOT · specialist", "卡槽 · 专家"),
    "svg_security": ("security", "安全"),
    "svg_slot_skeptic": ("SLOT · skeptic", "卡槽 · 唱反调"),
    "svg_attacker": ("attacker", "攻击者"),
    "svg_slot_survives": ("the slot survives", "卡槽还在"),
    "svg_roles_owned": ("roles are owned; models are rented", "角色是自己的；模型是租来的"),
    "svg_vendor_disappear": ("vendor disappears → slide in another. model deprecated → slot unchanged.", "供应商跑路 → 换一个。模型弃用 → 卡槽不动。"),
}


def escape_attr(text):
    return text.replace('&', '&amp;').replace('"', '&quot;').replace('<', '&lt;').replace('>', '&gt;')


if __name__ == "__main__":
    print(f"Post 1: {len(POST1)} entries")
    print(f"Post 2: {len(POST2)} entries")
