#!/usr/bin/env python3
"""
Chinese translations — written like a real Chinese person would write.
No translationese. No "它是一个深思熟虑且积极主动的模型" nonsense.
"""

# ─── Blog Post 1: The Loop Is the New Function ───
POST1 = {
    "date": ("July 24, 2026", "2026年7月24日"),
    "read": ("5 min read", "5 分钟阅读"),
    "title": ("The Loop Is the New Function", "循环取代了函数"),
    "deck": ("For 70 years the function was the atom of software. Now it's the loop. What changes when code stops running once and starts running forever?",
             "七十年来，函数是软件的基本单元。现在轮到循环了。当代码不再跑完就停，而是永远跑下去——一切都不一样了。"),

    "p1": ("Every programmer alive has internalized the same mental model: software is built from functions. You define an input, you write a transformation, you get an output. <code>f(x) = y</code>. The function is deterministic. It runs once. It stops. If it gives you the wrong answer, you debug the logic, fix it, run it again. This model is so deeply embedded in our tools, languages, and brains that we don't even question it anymore. It's just how software works.",
           "每个程序员骨子里都有同一个心智模型：软件就是一堆函数。定义输入，写好变换，拿到输出。<code>f(x) = y</code>。函数是确定的，跑一次，停。结果不对？调逻辑，改代码，再跑一遍。这套东西刻进了我们的工具、语言和直觉里，深到我们根本不会去质疑它——软件就是这样的。"),
    "p2": ("But something is shifting underneath us. The software being built in 2026 doesn't work like that. AI agents don't transform an input into an output and stop. They observe, act, evaluate, adjust, and repeat. They run in loops that don't have a clean termination condition. The fundamental unit isn't a function call — it's a cycle. And the engineering discipline emerging to design those cycles has a new name: loop engineering.",
           "但脚底下的地基在动。2026 年的软件不是这么玩的。AI 智能体不会把输入变成输出就收工。它们观察、行动、评估、调整，再来一轮。它们跑在没有明确终止条件的循环里。基本单元不再是函数调用，而是循环本身。专门设计这些循环的工程实践，有了一个新名字：循环工程。"),
    "caption1": ("The function runs and stops. The loop runs and learns. Different physics entirely.",
                 "函数跑完就停。循环会跑、会学。完全是两套物理规则。"),
    "h2_1": ("The death of determinism", "确定性已经死了"),
    "p3": ("Here's the uncomfortable truth nobody in the AI engineering discourse wants to say out loud: we lost determinism, and we're not getting it back. A function that calls an LLM is, by definition, not deterministic. The same input can produce different outputs on different days. This isn't a bug. It's the physics of the new substrate. And pretending otherwise — wrapping a model call in a function signature and hoping it behaves like <code>parseInt</code> — is the most common architectural mistake teams make in 2026.",
            "有个让人不舒服的事实，AI 工程圈没人愿意大声说出来：确定性没了，回不来了。调 LLM 的函数，本质上就不确定。同样的输入，今天和明天可能给出不同结果。这不是 bug，是新技术的物理特性。装作不是这样——把模型调用包进函数签名里，指望它像 <code>parseInt</code> 那样老实——是 2026 年团队最常犯的架构错误。"),
    "p4": ("Loop engineering accepts this reality and builds around it. Instead of trying to make models deterministic, you design systems that converge on correctness through repetition. The agent writes code, runs tests, reads the errors, and tries again. Each iteration isn't guaranteed to be right — but the loop, as a whole, is designed to converge. The engineering isn't in the individual step. It's in the shape of the cycle.",
           "循环工程接受这个现实，然后围绕它来设计。与其让模型变确定，不如设计一套通过反复迭代逼近正确的系统。智能体写代码、跑测试、看报错、再改。单次迭代不保证对——但整个循环被设计成会收敛。工程不在单步里，在循环的形状里。"),
    "caption2": ("A single function call starts wrong and stays wrong. A loop starts wrong and converges.",
                 "单次调用错了就一直错。循环会从错变对。"),
    "blockquote1": ("We spent 70 years optimizing for the fastest path from input to output. Now we're optimizing for the shortest path from wrong to right. Those are fundamentally different engineering problems.",
                    "七十年，我们一直在优化从输入到输出的最快路径。现在要优化的是从错到对的最短路径。这是两个根本不同的工程问题。"),
    "h2_2": ("What a loop engineer actually does", "循环工程师到底在干什么"),
    "p5": ('A traditional engineer asks: "How do I write the function that transforms this input into the correct output?" A loop engineer asks an entirely different set of questions: "How many iterations should this cycle take before I give up? What signal tells the agent it\'s done? What context needs to persist between iterations? Where does the feedback come from — tests, human review, another model? What\'s the cost ceiling per loop before this becomes uneconomic?"',
           '传统工程师问的是："怎么写出把输入变成正确输出的函数？" 循环工程师问的是完全不同的问题："这个循环跑几轮我该放弃？什么信号能告诉智能体该收工了？哪些上下文要跨迭代保留？反馈从哪来——测试、人审，还是另一个模型？每轮烧多少钱就不划算了？"'),
    "p6": ('These are not software engineering questions. They\'re closer to control theory — the discipline that gave us thermostats, autopilots, and cruise control. A thermostat doesn\'t "compute" the right temperature. It runs a loop: measure, compare, adjust, repeat. The correctness lives in the loop design, not in any single measurement. Loop engineering is essentially bringing control theory into software, whether we admit it or not.',
           '这些不是软件工程的问题。它们更像控制论——就是做恒温器、自动驾驶、定速巡航的那门学科。恒温器不会"算出"正确的温度。它跑循环：量、比、调、再来。正确性在循环设计里，不在某一次测量里。不管我们承不承认，循环工程本质上就是把控制论搬进了软件。'),
    "p7": ("The practical implications are wild. Your test suite isn't just a quality gate anymore — it's the feedback signal that keeps the loop converging. Your CI/CD pipeline isn't just deployment infrastructure — it's the harness that decides whether the agent's output is safe to ship. Your codebase isn't just a set of instructions — it's the context window that shapes what the agent does next. Everything gets reinterpreted through the lens of the loop.",
           "实际影响非常大。你的测试套件不再只是质量关卡——它是让循环收敛的反馈信号。你的 CI/CD 不再只是部署工具——它是决定智能体产出能不能上线的框架。你的代码库不再只是一堆指令——它是塑造智能体下一步行为的上下文。所有东西都要通过循环的视角重新理解。"),
    "h2_3": ("The harness is the product", "框架才是真正的产品"),
    "p8": ('This is why "harness engineering" keeps coming up in the same conversations as loop engineering. The harness is the scaffolding around the model: the system prompt, the tool definitions, the retrieval pipeline, the evaluation criteria, the retry logic, the guardrails. When your core compute is probabilistic, the deterministic wrapper around it becomes the actual product. OpenAI knows this — it\'s why Codex and ChatGPT Work are built as harnesses, not models. Anthropic knows it — Claude\'s tool-use protocol is a harness specification. The model is a commodity. The loop is the moat.',
           '这就是为什么"框架工程"总和循环工程一起被提起。框架是模型外围的脚手架：系统提示、工具定义、检索管线、评估标准、重试逻辑、安全边界。当你的核心计算是概率性的，外面那层确定性包装就成了真正的产品。OpenAI 懂这个——Codex 和 ChatGPT Work 是按框架来设计的，不是按模型。Anthropic 也懂——Claude 的工具调用协议就是一个框架规范。模型是商品，循环才是护城河。'),
    "caption3": ("The harness: deterministic scaffolding around a probabilistic core. This is the actual product.",
                 "框架：在概率性的核心外面包一层确定性。这才是真正的产品。"),
    "p9": ("I think most teams are still treating AI features as function calls with extra steps. They wrap a prompt in an API endpoint, ship it, and are confused when it works perfectly in testing and degrades in production. The degradation isn't a model problem. It's a loop problem. There's no feedback signal. No convergence criteria. No iteration. Just a single-shot function call that either works or doesn't, with no mechanism to improve itself.",
           "大多数团队还是把 AI 功能当成函数调用的升级版。写个 prompt，包成 API，发上线。测试时完美，一到生产就拉胯，然后一脸懵。退化不是模型的问题，是循环的问题。没反馈信号，没收敛标准，没迭代。就是一次性调用，成不成都没有自我纠错的机制。"),
    "p10": ('The teams winning at AI engineering in 2026 are the ones who stopped asking "how do I write this function?" and started asking "how do I design this loop?" The answer looks less like programming and more like gardening. You don\'t build a garden by placing each leaf. You design the conditions — soil, water, light — and let the system grow toward what you want. The loop is your garden bed. The model is the seed. Your job is to design the conditions for convergence.',
            '2026 年在 AI 工程上赢的团队，是那些不再问"这个函数怎么写"、而是问"这个循环怎么设计"的团队。答案不太像编程，更像种地。你不可能一片叶子一片叶子地摆。你设计的是条件——土、水、光——然后让系统朝你想要的方向长。循环是你的菜地，模型是种子。你的工作是设计收敛的条件。'),
    "p11": ("That's the shift. And it's bigger than any individual model release. The function was a good run. But the loop is where we live now.",
            "这就是转变。它比任何一次模型发布都大。函数的时代很好。但现在，循环才是我们住的地方。"),

    # SVG text elements
    "svg_classic_label": ("CLASSIC SOFTWARE", "传统软件"),
    "svg_input": ("input", "输入"),
    "svg_fx_det": ("deterministic · runs once", "确定性 · 跑一次"),
    "svg_output": ("output", "输出"),
    "svg_wrong_q": ("Wrong answer?", "结果不对？"),
    "svg_debug": ("Debug the function.", "调试函数。"),
    "svg_code_product": ("The code is the product.", "代码就是产品。"),
    "svg_ainative_label": ("AI-NATIVE SOFTWARE", "AI 原生软件"),
    "svg_observe": ("Observe", "观察"),
    "svg_observe_sub": ("read context", "读上下文"),
    "svg_act": ("Act", "行动"),
    "svg_act_sub": ("call tools", "调工具"),
    "svg_eval": ("Evaluate", "评估"),
    "svg_eval_sub": ("check result", "看结果"),
    "svg_adjust": ("Adjust", "调整"),
    "svg_adjust_sub": ("update plan", "改计划"),
    "svg_redesign": ("Redesign the loop.", "重新设计循环。"),
    "svg_harness_product": ("The harness is the product.", "框架才是产品。"),
    "svg_iterations": ("Iterations", "迭代次数"),
    "svg_error": ("Error", "误差"),
    "svg_converged": ("converged", "收敛"),
    "svg_attempt1": ("Attempt 1", "第 1 次"),
    "svg_attempt2": ("Attempt 2", "第 2 次"),
    "svg_attempt3": ("Attempt 3", "第 3 次"),
    "svg_single_call": ("Single function call →", "单次调用 →"),
    "svg_high_error": ("high error, no recovery", "误差大，不会自纠"),
    "svg_loop_converges": ("Loop converges →", "循环收敛 →"),
    "svg_error_zero": ("error → 0 over iterations", "误差趋零"),
    "svg_harness_label": ("THE HARNESS (deterministic)", "框架（确定性）"),
    "svg_sysprompt": ("System Prompt", "系统提示"),
    "svg_tooldefs": ("Tool Definitions", "工具定义"),
    "svg_rag": ("Retrieval (RAG)", "检索 (RAG)"),
    "svg_guardrails": ("Guardrails", "安全边界"),
    "svg_llm": ("LLM", "LLM"),
    "svg_prob": ("probabilistic", "概率性"),
    "svg_commodity": ("commodity", "商品"),
    "svg_testsuite": ("Test Suite", "测试套件"),
    "svg_evalcrit": ("Eval Criteria", "评估标准"),
    "svg_retrylogic": ("Retry Logic", "重试逻辑"),
    "svg_cicd": ("CI/CD Gate", "CI/CD 关卡"),
    "svg_feedback": ("feedback signal → next iteration", "反馈信号 → 下一轮"),
    "svg_context_in": ("context in", "上下文进"),
    "svg_signal_out": ("signal out", "信号出"),
}

# ─── Blog Post 2: Spaghetti With API Bills ───
POST2 = {
    "date": ("July 25, 2026", "2026年7月25日"),
    "read": ("6 min read", "6 分钟阅读"),
    "title": ("Spaghetti With API Bills", "意大利面和 API 账单"),
    "deck": ("Most multi-agent systems aren't architectures. They're distributed prompts with a billing problem. The fix is older than AI itself.",
             "大多数多智能体系统根本算不上架构。它们只是带账单问题的分布式 prompt。解药比 AI 老得多。"),

    "p1": ('Most teams building "multi-agent systems" in 2026 are not building systems. They have taken a single oversized prompt, sliced it across twenty agents, and called the result an architecture. The agents share ambiguous context. They return free-form text. They repeat each other\'s research and bill for the privilege. When one model\'s output format drifts — and it will drift — the entire chain collapses into a stack trace nobody can debug. This is not orchestration. It is spaghetti with API bills.',
           '2026 年大多数做"多智能体系统"的团队，做的不是系统。他们把一个过大的 prompt 切成二十份，分给二十个智能体，管这叫架构。智能体之间共享模糊的上下文，返回自由格式的文本，重复彼此的工作，还互相收费。某个模型的输出格式一漂移——一定会漂移——整条链就崩成一堆没人能调的 stack trace。这不叫编排，这叫意大利面加 API 账单。'),
    "p2": ('The pattern is common enough to be a punchline. A team reads that agents are the future, stands up a coordinator, fans out a dozen workers, wires them together with string and a JSON schema, and ships. For two weeks it looks like magic. Then reality arrives: token costs triple, latency balloons, outputs turn inconsistent, and nobody can explain why the system returned what it returned. The instinct is to blame the model. The model is rarely the problem. The problem is that there was never an architecture — only a distribution.',
           '这个套路已经普遍到能当笑话讲。团队看到智能体是未来，搭个协调器，铺十几个 worker，用 JSON schema 和胶水粘一粘，上线。前两周像魔法。然后现实来了：token 成本翻三倍，延迟起飞，输出开始不稳定，没人说得清系统为什么返回了那些东西。第一反应是怪模型。但模型很少是问题所在。问题是从来就没有架构——只有分发。'),
    "caption1": ("Distribution is not design. Tangled agents share ambiguity; a graph assigns each decision to exactly one node and every edge a contract.",
                 "分发不等于设计。纠缠的智能体共享模糊；图把每个决策交给一个节点，每条边都有契约。"),
    "h2_1": ("The two software crises", "两次软件危机"),
    "p3": ("The original software crisis, named in 1968, was defined by a single failure mode: systems had grown too large for any one person to understand. Code outgrew human comprehension, and the resulting bugs, overruns, and collapses felt existential. The discipline that emerged in response — modular decomposition, abstract data types, interfaces with contracts — was aimed at one specific terror. Every major idea in software engineering since, from objects to services to microservices, is a variation on the same move: break a large system into replaceable parts that speak to each other through strict contracts.",
           "1968 年命名的软件危机，核心就一个问题：系统大到了任何一个人都搞不懂的程度。代码超出了人脑的容量，bug、超期、崩溃接踵而来，感觉像要完蛋。后来发展出的一整套方法——模块化、抽象数据类型、带契约的接口——都是冲着这个恐惧去的。从那以后，软件工程几乎所有的大想法，从面向对象到服务化到微服务，都是同一个套路的不同版本：把大系统拆成可替换的零件，零件之间通过严格的契约交流。"),
    "p4": ("The new software crisis is the mirror image, and it is arriving faster. It is not too much code. It is too many agents with no architecture between them. An agent is a probabilistic component that produces unstructured output, drifts between versions, and costs money every time it runs. Wire enough of them together without contracts and you have rebuilt the 1968 crisis on a new substrate — except now the components lie, hallucinate, and send invoices.",
           "新的软件危机是镜像版，而且来得更快。问题不是代码太多，是智能体太多，中间没有架构。智能体是概率性组件，产出非结构化内容，版本间会漂移，每跑一次都花钱。把它们不加契约地连在一起，等于在新的底座上重建了 1968 年的危机——只不过现在这些零件会说谎、会幻觉、还会寄账单。"),
    "p5": ("The fix is the same fix, rediscovered. Graph engineering is the application of a fifty-year-old lesson to AI: one node owns one decision, one edge carries structured evidence, ordinary code handles the deterministic work, routers decide which branch continues, verifiers reject unsupported conclusions, and the strongest model sees only what survives.",
           "解药是同一个解药，重新被发现。图工程是把一个五十年的教训用在 AI 上：一个节点管一个决策，一条边承载结构化证据，普通代码干确定的活，路由器决定走哪条路，验证器砍掉站不住脚的结论，最强的模型只看活下来的东西。"),
    "caption2": ("The old crisis was unmanageable code; the new one is unmanaged agents. Both collapse into the same architectural cure.",
                 "旧危机是管不了的代码；新危机是管不了的智能体。两个的解药是同一个。"),
    "h2_2": ("Replaceability is the moat", "可替换才是护城河"),
    "p6": ("Here is the claim that matters most. The next durable advantage in AI will not be a single permanent model. It will be a system that keeps working when the model changes. Models are being swapped, repriced, deprecated, and leapfrogged every quarter. A system whose correctness depends on one irreplaceable model is a system with an expiration date. A system in which every node is replaceable is a system with a future.",
           "最重要的一句话：AI 领域下一个持久的优势，不会是某个永远不变的模型。而是一个在模型变了之后还能跑的系统。模型每个季度都在被换掉、改价、弃用、被超越。正确性绑死在某一个不可替换模型上的系统，是有保质期的。每个节点都能替换的系统，才有未来。"),
    "p7": ("This is what makes the graph, not the agent, the unit of value. In a well-designed graph, a cheap model handles extraction. A specialist inspects security. A skeptical agent attacks the result. A frontier model renders the final judgment — and it does so without ever carrying the entire workflow inside its context window. Each role is a slot. Each slot accepts any model that satisfies the contract. When a better model lands next month, it slides into the slot. When a vendor disappears, the slot survives.",
           "这就是为什么图才是价值单元，而不是智能体。在一个设计良好的图里，廉价模型做抽取，专家检查安全，怀疑论智能体来挑刺，前沿模型做最终裁决——而且它不需要把整个工作流塞进自己的上下文窗口。每个角色是一个插槽。每个插槽接受任何满足契约的模型。下个月出了更好的模型？插进去。供应商没了？插槽还在。"),
    "caption3": ("Roles are owned; models are rented. The architecture is the only durable asset.",
                 "角色是自己的，模型是租来的。架构才是唯一长久的资产。"),
    "blockquote1": ("The original software crisis taught engineers to stop writing programs and start writing replaceable parts. The agentic crisis will teach the same lesson, again, to a generation that thought it had skipped the class.",
                    "第一次软件危机教会了工程师：别再写程序了，开始写可替换的零件。智能体危机会把同一堂课再教一遍——给一代以为自己逃过这门课的人。"),
    "h2_3": ("The discipline returns", "老规矩回来了"),
    "p8": ("What is being rediscovered is not glamorous. It is interfaces, contracts, typed edges, separation of concerns. The novelty is that these ideas now govern not just deterministic code but probabilistic components that must be governed more strictly precisely because they are not trustworthy on their own. The graph is a discipline of distrust: structure compensates for the unreliability of the nodes.",
           "被重新发现的不是什么酷东西。就是接口、契约、类型化的边、关注点分离。新鲜的地方在于，这些理念现在管的不只是确定性代码，还有概率性组件——而且恰恰因为它们自己不可信，需要更严格地管。图是一种不信任的纪律：用结构来弥补节点的不靠谱。"),
    "p9": ("Notice what this discipline removes from the frontier model's shoulders. It no longer carries the whole workflow in one context window. It no longer has to be simultaneously the reader, the verifier, and the decider. The work is staged across a pipeline, and by the time a token reaches the strongest model, it has already been filtered, typed, and corroborated. The expensive model spends its budget on judgment, not on janitorial work. Costs fall. Latency falls. And, counterintuitively, quality rises — because every conclusion now arrives with a chain of evidence attached to it rather than the vibes of a single large prompt.",
           "注意这套纪律从前沿模型的肩上卸掉了什么。它不再需要把整个工作流塞进一个上下文窗口。它不再又当读者又当裁判又当决策者。工作在管道里分阶段处理，等 token 到达最强模型的时候，已经被过滤过、类型化过、交叉验证过了。贵的模型把预算花在判断上，不花在打杂上。成本降了，延迟降了。而且反直觉的是，质量也升了——因为现在每个结论都带着一条证据链，而不是一个大 prompt 的感觉。"),
    "p10": ("The teams that win will be the ones who stop measuring how clever their agents are and start measuring how replaceable they are. Cleverness is a property of the model, and the model is a borrowed asset. Replaceability is a property of the architecture, and the architecture is the only thing actually owned.",
            "能赢的团队，是那些不再衡量智能体有多聪明、而是衡量它们有多好换的团队。聪明是模型的属性，模型是借来的。可替换性是架构的属性，架构才是真正自己的。"),
    "p11": ("Spaghetti with API bills is the default state of multi-agent development in 2026. It is what happens when distribution is mistaken for design. The exit is older than the industry that needs it. Draw the graph. Type the edges. Make every node disposable. Then, and only then, does adding another agent make the system stronger instead of merely more expensive.",
            "意大利面加 API 账单，是 2026 年多智能体开发的默认状态。当你把分发当成了设计，就会变成这样。出路比需要它的行业还老。画图。类型化边。让每个节点都能扔。然后——只有然后——加一个智能体才会让系统更强，而不是更贵。"),

    # SVG elements
    "svg_dist_label": ("DISTRIBUTED PROMPT", "分布式 Prompt"),
    "svg_dist_sub": ("ambiguous context · repeated work · invoice per hop", "上下文模糊 · 重复干活 · 每跳一张账单"),
    "svg_graph_label": ("GRAPH ENGINEERING", "图工程"),
    "svg_rawinput": ("raw input", "原始输入"),
    "svg_extract": ("extract", "抽取"),
    "svg_router": ("router", "路由"),
    "svg_verify": ("verify", "验证"),
    "svg_judge": ("judge", "裁决"),
    "svg_evidence": ("evidence", "证据"),
    "svg_typed_edge": ("typed edge", "类型化边"),
    "svg_graph_sub": ("one node = one decision · every edge carries a contract", "一个节点 = 一个决策 · 每条边都有契约"),
    "svg_1968": ("1968 CRISIS", "1968 年危机"),
    "svg_too_code1": ("too much code", "代码太多"),
    "svg_too_code2": ("for one mind", "一个人搞不定"),
    "svg_2026": ("2026 CRISIS", "2026 年危机"),
    "svg_too_agents1": ("too many agents", "智能体太多"),
    "svg_too_agents2": ("no architecture", "没有架构"),
    "svg_replaceable": ("REPLACEABLE PARTS", "可替换零件"),
    "svg_strict_contracts": ("with strict contracts", "带严格契约"),
    "svg_same_lesson": ("the same lesson, twice", "同一堂课，学两遍"),
    "svg_any_model": ("ANY MODEL FITS THE CONTRACT", "任何模型都能插"),
    "svg_slot_extract": ("SLOT · extractor", "插槽 · 抽取"),
    "svg_cheap_model": ("cheap model", "廉价模型"),
    "svg_slot_specialist": ("SLOT · specialist", "插槽 · 专家"),
    "svg_security": ("security", "安全"),
    "svg_slot_skeptic": ("SLOT · skeptic", "插槽 · 怀疑者"),
    "svg_attacker": ("attacker", "攻击者"),
    "svg_slot_survives": ("the slot survives", "插槽还在"),
    "svg_roles_owned": ("roles are owned; models are rented", "角色是自己的；模型是租来的"),
    "svg_vendor_disappear": ("vendor disappears → slide in another. model deprecated → slot unchanged.", "供应商没了 → 换一个。模型弃用 → 插槽不变。"),
}


def escape_attr(text):
    """Escape text for use in HTML attribute value."""
    return text.replace('&', '&amp;').replace('"', '&quot;').replace('<', '&lt;').replace('>', '&gt;')


if __name__ == "__main__":
    print("Translation maps loaded.")
    print(f"Post 1: {len(POST1)} entries")
    print(f"Post 2: {len(POST2)} entries")
